apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  labels: 
    service: {{ .Values.labels.service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: 
      service: {{ .Values.selector.service }}
  template:
    metadata:
      labels: 
        service: {{ .Values.labels.service }}
    spec:
      containers:
      - name: {{ .Values.containers.name }}
        env:
          - name: CONFIG_SERVICE_PASSWORD
            value: {{ .Values.CONFIG_SERVICE_PASSWORD }}
          - name: NOTIFICATION_SERVICE_PASSWORD
            value: {{ .Values.NOTIFICATION_SERVICE_PASSWORD }}
          - name: STATISTICS_SERVICE_PASSWORD
            value: {{ .Values.STATISTICS_SERVICE_PASSWORD }}
          - name: ACCOUNT_SERVICE_PASSWORD
            value: {{ .Values.ACCOUNT_SERVICE_PASSWORD }}
          - name: MONGODB_PASSWORD
            value: {{ .Values.MONGODB_PASSWORD }}
        image: {{ .Values.image.repository }}  
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}


