apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
  labels: 
    service: {{ .Values.labels.service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
  selector: 
    service: {{ .Values.selector.service }}
  

