CONFIG_SERVICE_PASSWORD: password
NOTIFICATION_SERVICE_PASSWORD: password
STATISTICS_SERVICE_PASSWORD: password
ACCOUNT_SERVICE_PASSWORD: password
MONGODB_PASSWORD: password

image:
  repository: leonid132/piggymetrics-mongodb:latest
  pullPolicy: IfNotPresent
replicaCount: 1
metadata:
  name: notification-mongodb
labels:
  service: notificationmongodb
selector:
  service: notificationmongodb

service:
  type: ClusterIP
  port: 28000
  targetport: 27017

containers:
  name: notificationmongodb
serviceAccount:
  create: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

resources: 
  limits:
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
