CONFIG_SERVICE_PASSWORD: password
NOTIFICATION_SERVICE_PASSWORD: password
STATISTICS_SERVICE_PASSWORD: password
ACCOUNT_SERVICE_PASSWORD: password
MONGODB_PASSWORD: password

image:
  repository: leonid132/piggymetrics-statistics-service:latest        
  pullPolicy: IfNotPresent
replicaCount: 1
metadata:
  name: statisticsservice-deployment
labels:
  service: statisticsservice
selector:
  service: statisticsservice

service:
  type: ClusterIP
  port: 7000
  targetport: 7000

containers:
  name: statisticsservice
serviceAccount:
  create: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

ingress:
  enabled: false
  className: ""
  annotations: {}

  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: 
  limits:
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
